repos:
  - repo: https://github.com/nhtua/rayloc
    rev: v2026.10.7
    hooks:
      - id: rayloc-staged

  - repo: local
    hooks:
      - id: cargo-fmt-check
        name: cargo fmt check
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: cargo-clippy-check
        name: cargo clippy check
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
